### ISSUE TITLE
multiple path in one json

### ISSUE THREAD

**Issue by dkosasih** [release-it/bumper#10]
Currently it's not possible to specify multiple path in one json file. 
e.g. 
```
'./test.json,
{ file: 'test.json', path: 'dependencies.@myotherLib'}
```
Since the above is altering both `version` and `dependencies.@myotherlib` path within the same file and the file write file is happening in an async, the later will override the former. 

Would it be possible to make it so that `path` will accept array so I can alter multiple paths in json?

**Comment by webpro** [comment]
Hi @dkosasih, this has just been released in v1.4.0
