### ISSUE TITLE
Removing final carriage return from file breaking POSIX rules

### ISSUE THREAD

**Issue by TheRealWaldo** [release-it/bumper#12]
https://github.com/release-it/bumper/blob/b0cc7742c748520ab6276780f8c9eec79154a617/index.js#L44

Currently removes whitespace from the beginning and end of text files, which then breaks POSIX rules which state that there should be a carriage return on the last line of the file.

Is there any particular reason the trim needs to be there; if so, could we make it optional?

Happy to provide a patch, but a few routes, one is removing the trim (super easy), another is using an ltrim only, the final is another option (not so easy!)

**Comment by webpro** [comment]
Thanks @TheRealWaldo! I fixed it in v1.4.1, and also updated the tests.

**Comment by TheRealWaldo** [comment]
Thanks @webpro ! Working well!
