### ISSUE TITLE
require() of ES Module is not supported

### ISSUE THREAD

**Issue by Maybach91** [release-it/bumper#22]
Using the following command
`release-it prerelease --preRelease=alpha --gitlab.preRelease`

gets me the following error:
```bash
ERROR require() of ES Module /node_modules/@release-it/bumper/index.js from /node_modules/import-from/index.js not supported.
Instead change the require of /node_modules/@release-it/bumper/index.js in /node_modules/import-from/index.js to a dynamic import() which is available in all CommonJS modules.
```
My config:

```javascript
"plugins": {
    "@release-it/bumper": {
      "out": {
        "file": "./shopify/config/settings_schema.json",
        "path": "[0].theme_version"
      }
    }
  }
```

my file, where i want to update the version number:
```javascript
[
  {
    "name": "theme_info",
    "theme_version": "0.0.1",
  },
  ...
]
```

But no matter if i’m using a test file or a different path, i still get the error. i already have `@release-it/bumper@esm` installed.

**Comment by webpro** [comment]
Did you also `npm install release-it@latest` (v15)?

You can remove the `@esm` as the `@latest` of the plugin is also ESM.

**Comment by Maybach91** [comment]
> Did you also `npm install release-it@latest` (v15)?
> 
> You can remove the `@esm` as the `@latest` of the plugin is also ESM.
Thanks for your help @webpro !
I ran `yarn add -D @release-it/bumper` at first. But i think that installed only v14. 

I just installed `@latest` but i still get the same error.  I’m using node `v17.8.0` and yarn `3.2.0`
