### ISSUE TITLE
Option to force parsing a TOML file as text?

### ISSUE THREAD

**Issue by pastelmind** [release-it/bumper#23]
I'd like to update the version number in a `Cargo.toml` file, while preserving comments and whitespace. This is currently not possible because the round-trip through the TOML parser destroys all comments and reformats the file.

One alternative would be to force @release-it/bumper to parse it as text (thus using simple RegExp search and replace). I tried this by explicitly specifying `type: "text/plain"` in the config, but it didn't work--the program looks at the file extension of `Cargo.toml`, decides that it is TOML, and ignores the `type` option.

What if we had an `ignoreExt` option that makes @release-it/bumper ignore the file extension and only use the `type` option to determine the file type (with fallback to text)?

**Comment by webpro** [comment]
Sorry for the late reply. This was just a bug that should be fixed now in v4.0.2
