### ISSUE TITLE
When @releation-it /bumper4.0.0 is upgraded to 4.0.2, using the same.releation-it-json configuration, it Cannot read property 'toString' of null is throw

### ISSUE THREAD

**Issue by qianjunhu** [release-it/bumper#29]
When I was in **@release-it/bumper4.0.0**, I had a **.release-it.json** with the following configuration, but when I upgraded @release-it/bumper to **4.0.2**, when I run yarn run release-it, the following error will be thrown in the command window
![image](https://user-images.githubusercontent.com/88123567/212226393-717358c9-783a-4939-9b14-b10acb3b5fc5.png)

![image](https://user-images.githubusercontent.com/88123567/212225286-1cc6efd2-d186-4dd9-921c-b1c81c052989.png)

When I found the correction error was found here:
https://github.com/release-it/release-it/blob/5798a7a5a162432b9521cefe567dac1adcfc53d7/lib/index.js#L63

https://github.com/release-it/bumper/blob/2248567ec3d00dee6d52d1b66a6bc7c47e8ce1ae/index.js#L66
https://github.com/release-it/bumper/blob/2248567ec3d00dee6d52d1b66a6bc7c47e8ce1ae/index.js#L68

it worked when I changed the **.release-it-json** configuration to the following configuration
![image](https://user-images.githubusercontent.com/88123567/212225819-1eaef846-8ebd-44ba-95d7-d0d5b36a53a2.png)

When I checked the logic of file type conversion for package.json handled by release-it/bumper4.0.0 and 4.0.2 was different. Why would incompatibility be caused when upgrading the patch version?

**Comment by webpro** [comment]
> Why would incompatibility be caused when upgrading the patch version?

This patch bump was a bug fix. It made the plugin do what it should do, which is to override the file extension with the provided mime type.

If I may ask, why did you have `text/plain` as a mime type for `package.json`? I think that did nothing before the fix :)

**Comment by qianjunhu** [comment]
When I took on the project, it was using text/plain, and when I upgraded the **@releation-it /bumper**, I discovered the problem. Thank you very much for taking time out of your busy schedule to answer my doubts.
