### ISSUE TITLE
File bump should happen before release

### ISSUE THREAD

**Issue by alandtse** [release-it/bumper#5]
I understand that plugins [happen asynchronously](https://github.com/release-it/release-it/issues/501) but since this updates files, it should happen prior to the git/mercurial plugins so the newly updated files can be committed to git prior to github/gitlab.

**Comment by webpro** [comment]
The `bump` lifecyle methods of each plugin are executed prior to the `beforeRelease` and then `release` methods of each plugin. So it should work correctly. What is the issue for you? Can you share more details?

**Comment by alandtse** [comment]
Ok, I just realized I misread the logs during a dry-run. It does look like the proper files were bumped by bumper prior to the git commit. Sorry about the false alarm.
