### ISSUE TITLE
Replace version in non-standard files

### ISSUE THREAD

**Issue by AlecRust** [release-it/bumper#6]
I've had a good hunt through the issues on the release-it repos but can't find a clear answer on this (closest being https://github.com/release-it/release-it/issues/150).

As well as updating the version number in `package.json` I'd like to **find and replace** the version number in other non-JSON files.

I understand this should be done with a plugin since release-it v11, but was surprised that bumper didn't include the feature. I was hoping something like this would work:

```json
"plugins": {
  "@release-it/bumper": {
    "out": {
      "file": ["assets/styles/style.css", "functions.php", "readme.txt"],
      "type": "text/plain"
    }
  }
}
```

Can you tell me the recommended way to go about this if it's not this plugin? I need to update these other files to achieve a full WordPress theme release.

**Comment by webpro** [comment]
The `text/plain` file, as you probably notices, will contain only the version as its file contents. Some projects use e.g. a `VERSION` file with this.

For now, a workaround could look like this (without this plugin):

```
{
  "hooks": {
    "after:bump": ["sed -i 's/${latestVersion}/${version}/g' assets/styles/style.css functions.php readme.txt"]
  }
}
```

I'm happy to explore options for a nice API to replace the version number. Simply replacing the old version with the new version in a file is not safe, other instances of that string could be replaced as well. This is why I didn't implemented this initially.

**Comment by AlecRust** [comment]
Many thanks @webpro 👍
