### ISSUE TITLE
Allow Wildcards for out.file

### ISSUE THREAD

**Issue by aggrosoft** [release-it/bumper#8]
Currently the file path has to match a definite file, it would be useful to allow for wildcards. This would make it easy to bump the version in a set of files (e.g. commented file headers).

Are you open to pull requests for this?

**Comment by webpro** [comment]
Good idea! Thank you in advance.

**Comment by aggrosoft** [comment]
Implementation was pretty easy using [fast-glob](https://github.com/mrmlnc/fast-glob) - maybe you want  to have a look before I setup a pull request. Also I'm not good at writing tests, maybe somebody else could create a test for that.

See https://github.com/aggrosoft/bumper/commit/cf49289a1b4bca618f2221662dcdfbbc11157288

**Comment by webpro** [comment]
Thanks. I think there's no need for `glob: true` or something. We can just assume everything is "glob", making usage and implementation easier.

**Comment by aggrosoft** [comment]
I also tried without the option, but this makes it impossible to create a new file without glob (current functionality). If we introduce it like this it will be a BC for users that rely on creating new files if they do not exist.
